### PR TITLE
Support static and dynamic libraries

### PR DESCRIPTION
**Pull request by jakirkham**
This patch changes the CMake build so that it includes both static and dynamic libraries.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
@jakirkham can you rebase this please?

**Comment by ingydotnet** [comment]
@sigmavirus24, I rebased it and pushed to branch `issue/10`.

Wonder how to test this. @jakirkham?

**Comment by jakirkham** [comment]
I'm not really a Windows expert. I asked others for advice on how to get a dynamic and a static library and this is what they suggested.

Suppose one could do a file test to make sure it exists. Additionally one could try compiling some simple code and running it. What are your thoughts?

**Comment by jakirkham** [comment]
Also it looks like `master` has been rewritten. Why? 😕

**Comment by sigmavirus24** [comment]
@jakirkham This was not the canonical source when you submitted the pull request. When this became the canonical source, the history was rewritten when the repository was reimported.

**Comment by jakirkham** [comment]
Alright, I have tried to rebase this. Please let me know what you think.

**Comment by sigmavirus24** [comment]
Thanks @jakirkham!

**Pull request merged**
