### PR TITLE
fix token name typos in comments

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by vszakats** [comment]
Patch valid, but since it generated no interest, closing.

**Comment by perlpunk** [comment]
@vszakats you could have left it open. If maintainers aren't reacting it doesn't mean they aren't interested in it, they just don't have time problably ;-)

**Comment by vszakats** [comment]
@perlpunk Indeed! I prefer to close after a while to avoid having all the pending PRs piling up on the GitHub UI (I wish there was an 'archive' or 'forget' button there). I'm glad to reopen, in fact I upgraded my vendored copy of `libyaml` a few hours ago. I'm glad you picked up maintenance!

(To help vendored copy keepers, it'd be nice to have the libyaml version number `#define`s be rolled in the `.h` file directly instead of relying on make systems to s&r it into it. But I have no patch ready for this one :)

**Comment by vszakats** [comment]
New PR here: https://github.com/yaml/libyaml/pull/59

**Pull request closed without merging**
