### PR TITLE
Added alpine linux testing to dockerfiles

### PR DESCRIPTION
**Pull request by ingydotnet**
@sigmavirus24, could you add this alpine dockerfile to your appveyor test set?

### CODE REVIEW

**Comment by ingydotnet** [comment]
@sigmavirus24 semaphoreci is failing cuz I renamed dockerfiles to docker. Maybe just change the path for the new alpine entry and if it works then I can merge this and we can switch the rest.

**Comment by ingydotnet** [comment]
@sigmavirus24 fwiw I it's passing on my semaphoreci: https://semaphoreci.com/ingydotnet/libyaml/branches/docker-alpine/builds/6

**Comment by sigmavirus24** [comment]
I added you to semaphoreci, I think, I'm not sure if you want me to pre-emptively change the CI config before you merge or after.

**Comment by ingydotnet** [comment]
@sigmavirus24, very cool to add me. Thanks. I'll take care of everything then.
Mind if I merge this in?

**Pull request merged**
